spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      password: 123456
      username: root
      url: jdbc:mysql://localhost:3306/wintermilktea?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #修正swagger不匹配springboot2.6.*   Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。 解决： 修改application.yaml spring: mvc: pathmatch: matching-strategy: ANT_PATH_MATCHER
  application:
    name: springfox-swagger
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: cn.limitless.the_back_end.entity
  mapper-locations: classpath:cn/limitless/the_back_end/dao/impl/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
#debug日志开关
debug: false

#PageHelper
pagehelper:
  dialect: com.github.pagehelper.dialect.helper.MySqlDialect
  reasonable: true
  support-methods-arguments: true
  row-bounds-with-count: true
  offset-as-page-num: true


# ===== 自定义swagger配置 ===== # ${spring.application.name}
swagger:
  enable: true
  application-name: 冬至奶茶店
  application-version: 1.0
  application-description: springfox swagger 3.0整合
  try-host: http://localhost:${server.port}
